name: 🐛 Bug Report
description: Report a bug or issue.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to report this issue!

  - type: textarea
    attributes:
      label: What issue are you experiencing?
      description: Describe the bug or issue you encountered.

  - type: textarea
    attributes:
      label: What are the steps to reproduce the issue?
      description: Provide clear steps to reproduce the bug or issue.

  - type: textarea
    attributes:
      label: What behavior did you expect to see?
      description: Describe what you expected to happen.

  - type: textarea
    attributes:
      label: Any additional details?
      description: Include any additional information, such as error messages or screenshots.
