[c]
symbol = " "

[cmd_duration]
disabled = true

[directory]
read_only = " 󰌾"

[git_branch]
symbol = " "

[golang]
symbol = " "

[line_break]
disabled = true

[lua]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "
