[c]
symbol = " "

[cmd_duration]
disabled = true

[directory]
read_only = " 󰌾"

[docker_context]
symbol = "󰡨 "

[git_branch]
symbol = " "

[golang]
symbol = " "

[line_break]
disabled = true

[lua]
symbol = " "

[package]
symbol = '󰏗 '

[python]
symbol = " "

[rust]
symbol = " "
