format = """
$directory\
$git_branch\
$git_status\
$character\
"""

[directory]
style = "cyan"

[git_branch]
format = "[$branch](yellow) "

[git_status]
format = '([$all_status$ahead_behind](yellow) )'

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](purple)"
